networks:
    app_network:
        driver: bridge

services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
        volumes:
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/app
        depends_on:
            - php
        networks:
            - app_network

    mysql:
        image: mysql:8.1
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: set_reserve
        ports:
            - "3306:3306"
        volumes:
            - "./.docker/mysql:/var/lib/mysql/"
        networks:
            - app_network

    php:
        build:
            context: ./
            dockerfile: .docker/php/Dockerfile
        container_name: php
        entrypoint: .docker/docker-entrypoint.sh
        restart: unless-stopped
        tty: true
        expose:
            - "9000"
        volumes:
            - .:/var/www/app
        depends_on:
            - mysql
        networks:
            - app_network
        environment:
            XDEBUG_MODE: "coverage"

    redis:
        container_name: redis
        image: redis:6.2-alpine3.19@sha256:235003ac0ce6bc63b20323d2b180b76254383e886d317b632b7538680fed782b
        ports:
            - "6379:6379"
        networks:
            - app_network

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
            - xpack.security.transport.ssl.enabled=false
            - xpack.security.http.ssl.enabled=false
            - xpack.license.self_generated.type=trial
        ports:
            - 9200:9200
            - 9300:9300
        ulimits:
            memlock:
                soft: -1
                hard: -1
        networks:
            - app_network

    kibana:
        image: docker.elastic.co/kibana/kibana:8.14.3
        ports:
            - 5601:5601
        environment:
            ELASTICSEARCH_HOSTS: http://elasticsearch:9200
        networks:
            - app_network
