version: "3"

networks:
    app_network:
        driver: bridge

services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
        volumes:
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/app:delegated
        depends_on:
            - php
        networks:
            - app_network
    mysql:
        image: mysql:8.1
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: food_flow
        ports:
            - "3306:3306"
        volumes:
            - "./.docker/mysql:/var/lib/mysql/"
        networks:
            - app_network
    php:
        build:
            context: ./
            dockerfile: .docker/php/Dockerfile
        container_name: php
        restart: unless-stopped
        tty: true
        expose:
            - "9000"
        volumes:
            - .:/var/www/app:delegated
        depends_on:
            - mysql
        networks:
            - app_network
